import React, { useState } from 'react';
import { supabaseService } from '../supabaseService';
import { 
  Database, 
  Settings, 
  Terminal, 
  CheckCircle, 
  XCircle, 
  Copy, 
  RefreshCw, 
  Code, 
  Cpu, 
  HelpCircle,
  Eye,
  EyeOff,
  BookOpen
} from 'lucide-react';
import { translations } from '../translations';

interface SupabaseInstructionsProps {
  onConfigChanged: () => void;
  language: 'en' | 'bn';
  theme: 'dark' | 'light';
}

export default function SupabaseInstructions({ 
  onConfigChanged,
  language,
  theme
}: SupabaseInstructionsProps) {
  const [activeTab, setActiveTab] = useState<'bengali' | 'english' | 'sql' | 'php'>('bengali');
  const [copiedText, setCopiedText] = useState<string | null>(null);
  
  const currentConfig = supabaseService.getConfig();
  const [urlInput, setUrlInput] = useState(currentConfig.url);
  const [anonKeyInput, setAnonKeyInput] = useState(currentConfig.anonKey);
  const [tableNameInput, setTableNameInput] = useState(currentConfig.tableName);
  const [showKey, setShowKey] = useState(false);

  const [testStatus, setTestStatus] = useState<'idle' | 'loading' | 'success' | 'error'>('idle');
  const [testMessage, setTestMessage] = useState('');

  const t = translations[language];
  const isDark = theme === 'dark';

  const handleCopy = (text: string, id: string) => {
    navigator.clipboard.writeText(text);
    setCopiedText(id);
    setTimeout(() => setCopiedText(null), 2000);
  };

  const handleSaveConfig = (e: React.FormEvent) => {
    e.preventDefault();
    supabaseService.saveConfig(urlInput, anonKeyInput, tableNameInput);
    onConfigChanged();
    setTestStatus('idle');
    setTestMessage('');
  };

  const handleResetConfig = () => {
    supabaseService.resetConfig();
    const reset = supabaseService.getConfig();
    setUrlInput(reset.url);
    setAnonKeyInput(reset.anonKey);
    setTableNameInput(reset.tableName);
    onConfigChanged();
    setTestStatus('idle');
    setTestMessage('');
  };

  const handleTestConnection = async () => {
    setTestStatus('loading');
    const result = await supabaseService.testConnection();
    if (result.success) {
      setTestStatus('success');
      setTestMessage(result.message);
    } else {
      setTestStatus('error');
      setTestMessage(result.message);
    }
  };

  const sqlQueryString = `
-- 1. Run this table schema query in Supabase SQL Editor:
CREATE TABLE ${tableNameInput || 'login_logs'} (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  login_time TEXT,
  failed_time TEXT,
  logout_time TEXT,
  username TEXT NOT NULL,
  ip_address TEXT,
  site_url TEXT,
  location TEXT,
  user_agent TEXT,
  isp TEXT,
  status TEXT CHECK (status IN ('Logged In', 'Failed', 'Logged Out', 'Page Visit')),
  session_duration TEXT,
  visited_url TEXT
);

-- 2. Turn on Realtime Replication to catch updates stream instantly:
-- Go to Supabase > Database > Replication and toggle Source to ON for your logs table.
ALTER publication supabase_realtime ADD TABLE ${tableNameInput || 'login_logs'};

-- 3. Enable standard Row Level Security (RLS) policies:
ALTER TABLE ${tableNameInput || 'login_logs'} ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow anonymous read and insert" 
ON ${tableNameInput || 'login_logs'} 
FOR ALL 
TO anon 
USING (true) 
WITH CHECK (true);
`.trim();

  const phpSnippet = `
<?php
/**
 * Append this snippet into your active theme functions.php file.
 * It catches Successful Logins, Failed Attacks, and Page Visits,
 * and posts the telemetry payloads directly to your Supabase table.
 */

define('SUPABASE_URL', '${urlInput || 'YOUR_SUPABASE_PROJECT_URL'}');
define('SUPABASE_KEY', '${anonKeyInput || 'YOUR_SUPABASE_ANON_KEY'}');
define('SUPABASE_TABLE_NAME', '${tableNameInput || 'login_logs'}');

function post_to_supabase($payload_data) {
    if (!SUPABASE_URL || SUPABASE_URL === 'YOUR_SUPABASE_PROJECT_URL') return;
    $url = SUPABASE_URL . '/rest/v1/' . SUPABASE_TABLE_NAME;
    $headers = [
        'apikey: ' . SUPABASE_KEY,
        'Authorization: Bearer ' . SUPABASE_KEY,
        'Content-Type: application/json',
        'Prefer: return=minimal'
    ];

    $ch = curl_init($url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_POST, true);
    curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($payload_data));
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
    curl_exec($ch);
    curl_close($ch);
}

// Success Admin logs
add_action('wp_login', 'wp_security_log_successful_login', 10, 2);
function wp_security_log_successful_login($user_login, $user) {
    $geo = wp_security_get_geo_ip();
    post_to_supabase([
        'login_time' => current_time('iso'),
        'username' => $user_login,
        'ip_address' => $geo['ip'],
        'site_url' => get_site_url(),
        'location' => $geo['location'],
        'user_agent' => $_SERVER['HTTP_USER_AGENT'] ?? 'N/A',
        'isp' => $geo['isp'],
        'status' => 'Logged In',
        'visited_url' => $_SERVER['REQUEST_URI'] ?? ''
    ]);
}

// Failed Password attack logs
add_action('wp_login_failed', 'wp_security_log_failed_login');
function wp_security_log_failed_login($username) {
    $geo = wp_security_get_geo_ip();
    post_to_supabase([
        'failed_time' => current_time('iso'),
        'username' => $username,
        'ip_address' => $geo['ip'],
        'site_url' => get_site_url(),
        'location' => $geo['location'],
        'user_agent' => $_SERVER['HTTP_USER_AGENT'] ?? 'N/A',
        'isp' => $geo['isp'],
        'status' => 'Failed',
        'visited_url' => '/wp-login.php'
    ]);
}

function wp_security_get_geo_ip() {
    $ip = $_SERVER['REMOTE_ADDR'] ?? '127.0.0.1';
    $location = 'Unknown Location';
    $isp = 'Unknown ISP';
    
    $response = wp_remote_get("https://ipapi.co/{$ip}/json/");
    if (!is_wp_error($response)) {
        $body = json_decode(wp_remote_retrieve_body($response), true);
        if ($body) {
            $location = ($body['city'] ?? '') . ', ' . ($body['country_name'] ?? '');
            $isp = $body['org'] ?? 'ISP N/A';
        }
    }
    return ['ip' => $ip, 'location' => $location, 'isp' => $isp];
}
`.trim();

  return (
    <div id="supabase-guide-container" className={`border rounded-2xl overflow-hidden transition-all duration-200 ${
      isDark ? 'bg-[#111420] border-gray-800' : 'bg-white border-slate-200 shadow-sm'
    }`}>
      {/* Header */}
      <div className={`px-6 py-5 border-b flex items-center justify-between flex-col sm:flex-row gap-3 ${
        isDark ? 'bg-[#171b2d] border-gray-800' : 'bg-slate-50 border-slate-100'
      }`}>
        <div className="flex items-center gap-3">
          <div className="p-2.5 bg-emerald-500/10 rounded-xl text-emerald-500">
            <Database className="w-5 h-5" />
          </div>
          <div>
            <h2 className={`text-base font-bold tracking-tight ${isDark ? 'text-white' : 'text-slate-900'}`}>{t.settingsTitle}</h2>
            <p className={`text-xs ${isDark ? 'text-gray-400' : 'text-slate-500'}`}>{t.settingsSub}</p>
          </div>
        </div>

        <div>
          <span className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-semibold ${
            currentConfig.isConfigured ? 'bg-emerald-500/10 text-emerald-500' : 'bg-amber-500/10 text-amber-500'
          }`}>
            <span className={`w-1.5 h-1.5 rounded-full ${currentConfig.isConfigured ? 'bg-emerald-500' : 'bg-amber-500 animate-pulse'}`} />
            {currentConfig.isConfigured ? t.liveMode : t.sandboxMode}
          </span>
        </div>
      </div>

      <div className={`grid grid-cols-1 lg:grid-cols-12 divide-y lg:divide-y-0 lg:divide-x ${
        isDark ? 'divide-gray-800' : 'divide-slate-200'
      }`}>
        
        {/* Left Column: DB overrides Parameter config */}
        <div className="lg:col-span-5 p-6 space-y-6">
          <div className="space-y-1.5">
            <h3 className={`text-xs font-bold uppercase tracking-wider flex items-center gap-2 ${isDark ? 'text-gray-250' : 'text-slate-700'}`}>
              <Settings className="w-4 h-4 text-emerald-500" />
              {t.settingsGlow}
            </h3>
            <p className={`text-xs leading-relaxed ${isDark ? 'text-gray-400' : 'text-slate-500'}`}>
              {t.settingsGlowDesc}
            </p>
          </div>

          <form onSubmit={handleSaveConfig} className="space-y-4">
            <div>
              <label className={`block text-[10px] font-bold uppercase tracking-wider mb-1.5 ${isDark ? 'text-gray-400' : 'text-slate-400'}`}>
                {t.urlLabel}
              </label>
              <input
                type="url"
                required
                value={urlInput}
                onChange={(e) => setUrlInput(e.target.value)}
                placeholder="https://your-wp-project.supabase.co"
                className={`w-full rounded-xl px-3.5 py-2.5 text-xs focus:outline-none focus:border-emerald-500 font-mono transition-colors ${
                  isDark ? 'bg-[#121826] text-gray-200 border border-gray-800' : 'bg-slate-100 text-slate-800 border border-slate-250'
                }`}
              />
            </div>

            <div>
              <label className={`block text-[10px] font-bold uppercase tracking-wider mb-1.5 flex items-center justify-between ${isDark ? 'text-gray-400' : 'text-slate-400'}`}>
                <span>{t.anonLabel}</span>
                <button
                  type="button"
                  onClick={() => setShowKey(!showKey)}
                  className="text-slate-400 hover:text-emerald-500 transition-colors"
                >
                  {showKey ? <EyeOff className="w-3.5 h-3.5" /> : <Eye className="w-3.5 h-3.5" />}
                </button>
              </label>
              <input
                type={showKey ? 'text' : 'password'}
                required
                value={anonKeyInput}
                onChange={(e) => setAnonKeyInput(e.target.value)}
                placeholder="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                className={`w-full rounded-xl px-3.5 py-2.5 text-xs focus:outline-none focus:border-emerald-500 font-mono transition-colors ${
                  isDark ? 'bg-[#121826] text-gray-200 border border-gray-800' : 'bg-slate-100 text-slate-800 border border-slate-250'
                }`}
              />
            </div>

            <div>
              <label className={`block text-[10px] font-bold uppercase tracking-wider mb-1.5 ${isDark ? 'text-gray-400' : 'text-slate-400'}`}>
                {t.tableLabel}
              </label>
              <input
                type="text"
                required
                value={tableNameInput}
                onChange={(e) => setTableNameInput(e.target.value)}
                placeholder="login_logs"
                className={`w-full rounded-xl px-3.5 py-2.5 text-xs focus:outline-none focus:border-emerald-500 font-mono ${
                  isDark ? 'bg-[#121826] text-gray-200 border border-gray-800' : 'bg-slate-100 text-slate-800 border border-slate-250'
                }`}
              />
            </div>

            <div className="flex gap-2">
              <button
                type="submit"
                className="flex-1 bg-emerald-500 hover:bg-emerald-600 text-slate-950 font-black rounded-xl text-xs py-2.5 px-4 transition-all duration-200 cursor-pointer text-center"
              >
                {t.saveConfigBtn}
              </button>
              {(urlInput || anonKeyInput) && (
                <button
                  type="button"
                  onClick={handleResetConfig}
                  className={`font-semibold rounded-xl text-xs px-3.5 py-2.5 transition-colors cursor-pointer border ${
                    isDark ? 'bg-gray-800 hover:bg-gray-750 text-gray-300 border-gray-700' : 'bg-slate-100 hover:bg-slate-200 text-slate-700 border-slate-200'
                  }`}
                >
                  {t.resetBtn}
                </button>
              )}
            </div>
          </form>

          {/* Verification Engine */}
          {currentConfig.isConfigured && (
            <div className={`rounded-xl p-4 border space-y-3 ${isDark ? 'bg-[#0b0c16] border-gray-800' : 'bg-slate-50 border-slate-200'}`}>
              <div className="flex items-center justify-between">
                <span className={`text-xs font-bold uppercase tracking-wider ${isDark ? 'text-gray-400' : 'text-slate-500'}`}>
                  {t.connCheckedTitle}
                </span>
                <button
                  onClick={handleTestConnection}
                  disabled={testStatus === 'loading'}
                  className="text-xs text-emerald-500 hover:text-emerald-400 font-bold flex items-center gap-1 transition-colors cursor-pointer disabled:opacity-55"
                >
                  <RefreshCw className={`w-3 h-3 ${testStatus === 'loading' ? 'animate-spin' : ''}`} />
                  {t.connCheckedRun}
                </button>
              </div>

              {testStatus === 'success' && (
                <div className="flex gap-2.5 text-emerald-500 text-xs bg-emerald-500/5 p-2.5 rounded-lg border border-emerald-500/20 leading-relaxed font-sans">
                  <CheckCircle className="w-4 h-4 shrink-0 mt-0.5" />
                  <span>{testMessage}</span>
                </div>
              )}

              {testStatus === 'error' && (
                <div className="flex gap-2.5 text-red-500 text-xs bg-red-500/5 p-2.5 rounded-lg border border-red-500/20 leading-relaxed font-sans">
                  <XCircle className="w-4 h-4 shrink-0 mt-0.5" />
                  <span>{testMessage}</span>
                </div>
              )}
            </div>
          )}

          <div className={`rounded-xl p-4 border text-xs leading-relaxed space-y-2 ${
            isDark ? 'bg-[#171b2d]/40 border-gray-800' : 'bg-slate-50 border-slate-200'
          }`}>
            <h4 className={`font-bold flex items-center gap-1.5 text-xs ${isDark ? 'text-white' : 'text-slate-800'}`}>
              <BookOpen className="w-4 h-4 text-emerald-400" />
              {t.connDocTitle}
            </h4>
            <ul className={`list-decimal pl-4 space-y-2 ${isDark ? 'text-gray-400' : 'text-slate-600'}`}>
              <li>{t.connDocList1}</li>
              <li>{t.connDocList2}</li>
              <li>{t.connDocList3}</li>
            </ul>
          </div>
        </div>

        {/* Right Column: Code viewer tabs */}
        <div className="lg:col-span-7 flex flex-col min-h-[440px]">
          {/* Tabs header nav */}
          <div className={`border-b flex overflow-x-auto ${isDark ? 'bg-[#151829] border-gray-800' : 'bg-slate-50 border-slate-200'}`}>
            <button
              onClick={() => setActiveTab('bengali')}
              className={`px-5 py-3.5 text-xs font-bold whitespace-nowrap border-b-2 transition-colors cursor-pointer ${
                activeTab === 'bengali' 
                  ? 'border-emerald-500 text-emerald-500 bg-emerald-500/5' 
                  : `border-transparent ${isDark ? 'text-gray-400 hover:text-white' : 'text-slate-500 hover:text-slate-900'}`
              }`}
            >
              {t.tabDocBangla}
            </button>
            <button
              onClick={() => setActiveTab('sql')}
              className={`px-5 py-3.5 text-xs font-bold whitespace-nowrap border-b-2 transition-colors cursor-pointer ${
                activeTab === 'sql' 
                  ? 'border-emerald-500 text-emerald-500 bg-emerald-500/5' 
                  : `border-transparent ${isDark ? 'text-gray-400 hover:text-white' : 'text-slate-500 hover:text-slate-900'}`
              }`}
            >
              {t.tabDocSql}
            </button>
            <button
              onClick={() => setActiveTab('php')}
              className={`px-5 py-3.5 text-xs font-bold whitespace-nowrap border-b-2 transition-colors cursor-pointer ${
                activeTab === 'php' 
                  ? 'border-emerald-500 text-emerald-500 bg-emerald-500/5' 
                  : `border-transparent ${isDark ? 'text-gray-400 hover:text-white' : 'text-slate-500 hover:text-slate-900'}`
              }`}
            >
              {t.tabDocPhp}
            </button>
            <button
              onClick={() => setActiveTab('english')}
              className={`px-5 py-3.5 text-xs font-bold whitespace-nowrap border-b-2 transition-colors cursor-pointer ${
                activeTab === 'english' 
                  ? 'border-emerald-500 text-emerald-500 bg-emerald-500/5' 
                  : `border-transparent ${isDark ? 'text-gray-400 hover:text-white' : 'text-slate-500 hover:text-slate-900'}`
              }`}
            >
              {t.tabDocEng}
            </button>
          </div>

          {/* Show target tab content code */}
          <div className="flex-1 p-6 overflow-y-auto max-h-[460px]">
            {activeTab === 'bengali' && (
              <div className={`space-y-4 text-xs leading-relaxed ${isDark ? 'text-gray-400' : 'text-slate-600'}`}>
                <div className="border-l-2 border-emerald-500 pl-4 py-1">
                  <h4 className={`font-bold text-xs mb-1 ${isDark ? 'text-white' : 'text-slate-900'}`}>{t.bengaliGuideTitle}</h4>
                  <p>{t.bengaliGuideDesc}</p>
                </div>

                <div className="border-l-2 border-emerald-500 pl-4 py-1">
                  <h4 className={`font-bold text-xs mb-1 ${isDark ? 'text-white' : 'text-slate-900'}`}>{t.bengaliGuideTitle2}</h4>
                  <p>{t.bengaliGuideDesc2}</p>
                </div>

                <div className="border-l-2 border-emerald-500 pl-4 py-1">
                  <h4 className={`font-bold text-xs mb-1 ${isDark ? 'text-white' : 'text-slate-900'}`}>{t.bengaliGuideTitle3}</h4>
                  <p>{t.bengaliGuideDesc3}</p>
                </div>

                <div className="border-l-2 border-emerald-500 pl-4 py-1">
                  <h4 className={`font-bold text-xs mb-1 ${isDark ? 'text-white' : 'text-slate-900'}`}>{t.bengaliGuideTitle4}</h4>
                  <p>{t.bengaliGuideDesc4}</p>
                </div>
              </div>
            )}

            {activeTab === 'english' && (
              <div className={`space-y-4 text-xs leading-relaxed ${isDark ? 'text-gray-400' : 'text-slate-600'}`}>
                <div className="border-l-2 border-emerald-500 pl-4 py-1">
                  <h4 className={`font-bold text-xs mb-1 ${isDark ? 'text-white' : 'text-slate-900'}`}>Step 1: Create Database Schema</h4>
                  <p>
                    Log into Supabase dashboard, navigate to the <strong>SQL Editor</strong> tab on the left. Click on new blank query and run the raw SQL schema code inside the SQL Schema query tab above. This correctly spawns the PostgreSQL <code className="font-mono text-emerald-500">{tableNameInput}</code> table on your project cloud instance.
                  </p>
                </div>

                <div className="border-l-2 border-emerald-500 pl-4 py-1">
                  <h4 className={`font-bold text-xs mb-1 ${isDark ? 'text-white' : 'text-slate-900'}`}>Step 2: Enable Real-time Publication</h4>
                  <p>
                    To listen to raw SQL modifications streaming dynamically on this client without forcing manual page hard refreshes, navigate to <code className="text-emerald-500 text-[11px]">Database &gt; Replication</code> menu inside Supabase, and toggle target tables Source stream to ON.
                  </p>
                </div>

                <div className="border-l-2 border-emerald-500 pl-4 py-1">
                  <h4 className={`font-bold text-xs mb-1 ${isDark ? 'text-white' : 'text-slate-900'}`}>Step 3: WordPress function.php cURL Hooks Integration</h4>
                  <p>
                    Open your active target layout theme <code className="font-mono">functions.php</code> file inside WordPress. Deploy the PHP functions template on the right side. It registers actions to capture password attack parameters as they occur.
                  </p>
                </div>
              </div>
            )}

            {activeTab === 'sql' && (
              <div className="space-y-3">
                <div className="flex items-center justify-between">
                  <span className="text-[10px] text-gray-450 font-mono">Create SQL Table & Enable RLS Policy</span>
                  <button
                    onClick={() => handleCopy(sqlQueryString, 'sql')}
                    className="text-xs text-emerald-500 hover:text-emerald-400 font-bold flex items-center gap-1 cursor-pointer"
                  >
                    <Copy className="w-3.5 h-3.5" />
                    <span>{copiedText === 'sql' ? (language === 'bn' ? 'কপি হয়েছে!' : 'Copied!') : (language === 'bn' ? 'কপি করুন' : 'Copy SQL')}</span>
                  </button>
                </div>
                <pre className={`p-4 rounded-xl border font-mono text-[10px] overflow-x-auto whitespace-pre leading-relaxed select-all ${
                  isDark ? 'bg-[#050308] border-gray-950 text-emerald-400' : 'bg-slate-100 border-slate-200 text-emerald-800'
                }`}>
                  {sqlQueryString}
                </pre>
              </div>
            )}

            {activeTab === 'php' && (
              <div className="space-y-3">
                <div className="flex items-center justify-between">
                  <span className="text-[10px] text-gray-450 font-mono">WordPress functions.php hook webhook code</span>
                  <button
                    onClick={() => handleCopy(phpSnippet, 'php')}
                    className="text-xs text-emerald-500 hover:text-emerald-400 font-bold flex items-center gap-1 cursor-pointer"
                  >
                    <Copy className="w-3.5 h-3.5" />
                    <span>{copiedText === 'php' ? (language === 'bn' ? 'কপি হয়েছে!' : 'Copied!') : (language === 'bn' ? 'কপি করুন' : 'Copy PHP')}</span>
                  </button>
                </div>
                <pre className={`p-4 rounded-xl border font-mono text-[10px] overflow-x-auto whitespace-pre leading-relaxed select-all ${
                  isDark ? 'bg-[#030607] border-gray-950 text-sky-400' : 'bg-slate-100 border-slate-200 text-sky-800'
                }`}>
                  {phpSnippet}
                </pre>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
